language: go

go:
- "1.14"

os:
  - linux
services:
  - docker  

install:
  - go get -u github.com/ains/go-test-html
#   - go get github.com/project-flogo/cli/...
#   - go get github.com/project-flogo/rules/...
#   - go get github.com/project-flogo/legacybridge
#   - go get github.com/imdario/mergo

# before_script:
#   - curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
#   - sudo apt-get install apt-transport-https --yes
#   - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
#   - sudo apt-get update
#   - sudo apt-get install helm

script:
  - wget https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz
  - tar -zxvf helm-v3.1.1-linux-amd64.tar.gz
  - sudo mv linux-amd64/helm /usr/local/bin/helm
  - helm version
  
notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
      - ${EMAILAD}
